version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: fullStackSiman                
      POSTGRES_USER: postgres                    
      POSTGRES_PASSWORD: ah18059                 
    ports:
      - "5434:5432"                              
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d               

  backend:
    build:
      context: ./fullstack-bakend/fullstack-bakend  
    container_name: backend_app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fullStackSiman
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ah18059
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./productos-app                    
    container_name: frontend_app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
